name: Close All Non-Contrib Pull Requests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: kyllingene/close-pr@v1
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We do not accept PRs from unauthorized people."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
